<html>
Recall the from the notes the 'finally' clause of a try statement. This clause allows you to
execute code regardless of whether or not there is an exception thrown. In this exercise we have
given you a loop: the first time through the loop there is an error because of an attempted
division by zero.  However, we still want to print to the user that the loop executed.<br><br>

Add a try statement in the loop that has an except clause AND a finally clause.
The except clause should print a message to the user informing them that a division by zero
was attempted.  The finally clause should print out how many times we have been through the loop.
<br>
</html>